name: CI Pipeline

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    name: Build and test all
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore solution dependencies
      run: dotnet restore ./OAuthOpenIdSolution/OAuthOpenIdSolution.sln

    - name: Build solution
      run: dotnet build ./OAuthOpenIdSolution/OAuthOpenIdSolution.sln --no-restore --configuration Release

    - name: Test (if any test projects exist)
      run: dotnet test ./OAuthOpenIdSolution/OAuthOpenIdSolution.sln --no-build --verbosity normal

