name: CI Pipeline (Matrix + Build)

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    name: Build OAuthOpenIdSolution
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore solution dependencies
      run: dotnet restore ./OAuthOpenIdSolution/OAuthOpenIdSolution.sln

    - name: Build solution
      run: dotnet build ./OAuthOpenIdSolution/OAuthOpenIdSolution.sln --no-restore --configuration Release

    - name: Test (if any test projects exist)
      run: dotnet test ./OAuthOpenIdSolution/OAuthOpenIdSolution.sln --no-build --verbosity normal

  build-matrix:
    name: Build and Test Matrix (GPU/CPU runners)
    runs-on: [self-hosted, ${{ matrix.target }}]
    timeout-minutes: 15
    strategy:
      matrix:
        target: [gpu, cpu]
    steps:
    - name: Print runner info
      run: |
        echo "Runner OS: ${{ runner.os }}"
        echo "Runner name: ${{ runner.name }}"
        echo "Target: ${{ matrix.target }}"
    - name: Simulate build
      run: |
        echo "Build project for target: ${{ matrix.target }}"
        sleep 10
    - name: Simulate test
      run: |
        echo "Running test for target: ${{ matrix.target }}"
        sleep 5
    
    - name: Deploy (CPU only)
      if: ${{ matrix.target == 'cpu' }}
      run: echo "Deploying for CPU target..."
      

