name: CI Pipeline (Matrix + Build)

on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  build:
    name: Build OAuthOpenIdSolution
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore solution dependencies
      run: dotnet restore ./OAuthOpenIdSolution/OAuthOpenIdSolution.sln

    - name: Build solution
      run: dotnet build ./OAuthOpenIdSolution/OAuthOpenIdSolution.sln --no-restore --configuration Release

    - name: Test (if any test projects exist)
      run: dotnet test ./OAuthOpenIdSolution/OAuthOpenIdSolution.sln --no-build --verbosity normal
  test-cpu:
    name: Run Tests on CPU Runner
    needs: build
    runs-on: [self-hosted, cpu]
    steps:
    - name: Print runner info
      run: |
        echo "Runner OS: ${{ runner.os }}"
        echo "Runner name: ${{ runner.name }}"
        echo "Target: cpu"
    - name: Simulate build
      run: |
        echo "Build project for target: cpu"
        sleep 10
    - name: Simulate test
      run: |
        echo "Running test for target: cpu"
        sleep 5
    
    - name: Deploy for cpu
      run: echo "Deploying for CPU target..."

  test-gpu:
    name: Run Tests on GPU Runner
    needs: build
    runs-on: [self-hosted, gpu]
    steps:
    - name: Print runner info
      run: |
        echo "Runner OS: ${{ runner.os }}"
        echo "Runner name: ${{ runner.name }}"
        echo "Target: gpu"
    - name: Simulate build
      run: |
        echo "Build project for target: gpu"
        sleep 10
    - name: Simulate test
      run: |
        echo "Running test for target: gpu"
        sleep 5
    
    - name: Deploy for gpu
      run: echo "Deploying for gPU target..."
      

